[[mod]]
name = "ComputerCraft1.72.jar"
url  = "http://minecraft.curseforge.com/mc-mods/67504-computercraft/files/2228723/download"

[[mod]]
name = "chocolateQuest-1.7.10-1.0.jar"
url  = "http://addons.curse.cursecdn.com/files/2227/53/chocolateQuest-1.7.10-1.0.jar"

[[resourcepack]]
name = "ocdpack187113693.zip"
url  = "http://static.planetminecraft.com/files/resource_media/texture/1436/ocdpack187113693.zip"
