[[mod]]
name = "ComputerCraft1.72.jar"
url  = "http://minecraft.curseforge.com/mc-mods/67504-computercraft/files/2228723/download"

[[mod]]
name = "chocolateQuest-1.7.10-1.0.jar"
url  = "http://addons.curse.cursecdn.com/files/2227/53/chocolateQuest-1.7.10-1.0.jar"

[[mod]]
name = "Bamboo-2.6.8.3.jar"
url  = "https://dl.dropboxusercontent.com/u/37248864/Bamboo-2.6.8.3.jar"
